//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTStoreManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string MaND { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string ChucVu { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Anh { get; set; }
        public string DiaChi { get; set; }
        public bool GioiTinh { get; set; }
    }
}
