//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTStoreManager2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangDonHangXuat
    {
        public string MaDHX { get; set; }
        public string MaH { get; set; }
        public int SoLuong { get; set; }
    
        public virtual DonHangXuat DonHangXuat { get; set; }
        public virtual Hang Hang { get; set; }
    }
}
